apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: test-ctse-lab-10-2022
  name: test-ctse-lab-10-2022
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-ctse-lab-10-2022
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-ctse-lab-10-2022
    spec:
      containers:
        - image: it19186948/ctse-lab-10-2022:a756d25d9ae6db9b626011505f5e80f3139e4124
          imagePullPolicy: Always
          name: ctse-lab-10-2022
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
