apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-ctse-lab-10-2022
  name: test-ctse-lab-10-2022
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: test-ctse-lab-10-2022
status:
  loadBalancer: {}
